In [3]:
import numpy as np
import pandas as pd

In [7]:
array1 = np.array([1,2,3,4])

In [8]:
array1

array([1, 2, 3, 4])

In [10]:
numbers = [9,8,7,6]
array_two = np.array(numbers)
array_two


array([9, 8, 7, 6])

In [13]:
array_zeros = np.zeros((3,4))
array_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
array_zeros.shape

(3, 4)

In [15]:
array_of_ones = np.ones((3,4))
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
array_of_ones = np.ones(4)
array_of_ones

array([1., 1., 1., 1.])

In [17]:
array_of_ones_int = np.ones((3,4),dtype=np.int16)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [18]:
array_empty = np.empty((2,3))  
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
array_eye = np.eye(4,4)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
array_eye = np.eye(4,4,1)
array_eye

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [28]:
array_of_evens = np.arange(2, 20, 2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
array_of_floats = np.arange( 0, 2, 0.3 , dtype = np.float64)
array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [33]:
array_2d = np.array([(2,4,6),(3,5,7)]) 
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [34]:
array_2d.shape

(2, 3)

In [35]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [39]:
array_nd = np.arange(6).reshape(2,3) 
array_nd

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
array_nd = np.arange(6).reshape(3,2) 
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [42]:
array_nd = np.arange(6).reshape(3,4) 
array_nd

ValueError: cannot reshape array of size 6 into shape (3,4)

In [43]:
array_of_ones = np.ones(array_nd.shape)
array_of_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [44]:
array_ones = np.ones_like(array_nd)
array_ones

array([[1, 1],
       [1, 1],
       [1, 1]])